name: jjxpytorchlearn
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - appnope=0.1.4=py310hca03da5_0
  - argon2-cffi-bindings=25.1.0=py310h254cc4a_0
  - asttokens=3.0.0=py310hca03da5_0
  - async-lru=2.0.5=py310hca03da5_0
  - attrs=25.4.0=py310hca03da5_2
  - brotlicffi=1.0.9.2=py310h50f4ffc_2
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - certifi=2025.10.5=py310hca03da5_0
  - cffi=2.0.0=py310h73c2a22_1
  - charset-normalizer=3.4.4=py310hca03da5_0
  - decorator=5.2.1=py310hca03da5_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.3.0=py310hca03da5_0
  - executing=2.2.1=py310hca03da5_0
  - expat=2.7.3=h982b769_0
  - h11=0.16.0=py310hca03da5_1
  - httpcore=1.0.9=py310hca03da5_0
  - httpx=0.28.1=py310hca03da5_1
  - idna=3.11=py310hca03da5_0
  - jedi=0.19.2=py310hca03da5_0
  - jinja2=3.1.6=py310hca03da5_0
  - jupyter_client=8.6.3=py310hca03da5_0
  - jupyter_core=5.8.1=py310hca03da5_0
  - jupyter_events=0.12.0=py310hca03da5_0
  - jupyter_server=2.16.0=py310hca03da5_0
  - jupyter_server_terminals=0.5.3=py310hca03da5_0
  - jupyterlab_pygments=0.3.0=py310hca03da5_0
  - jupyterlab_server=2.28.0=py310hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libsodium=1.0.20=h897f8a9_0
  - libzlib=1.3.1=h5f15de7_0
  - matplotlib-inline=0.2.1=py310hca03da5_0
  - nb_conda_kernels=2.5.2=py310hca03da5_2
  - nbclient=0.10.2=py310hca03da5_0
  - nbconvert-core=7.16.6=py310hca03da5_0
  - nbformat=5.10.4=py310hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py310hca03da5_0
  - notebook-shim=0.2.4=py310hca03da5_0
  - openssl=3.0.18=h9b4081a_0
  - overrides=7.7.0=py310hca03da5_0
  - packaging=25.0=py310hca03da5_1
  - pandocfilters=1.5.1=py310hca03da5_0
  - parso=0.8.5=py310hca03da5_0
  - pexpect=4.9.0=py310hca03da5_1
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=py310hca03da5_0
  - prometheus_client=0.21.1=py310hca03da5_0
  - prompt-toolkit=3.0.52=py310hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310hca03da5_0
  - pycparser=2.23=py310hca03da5_0
  - pygments=2.19.2=py310hca03da5_0
  - pysocks=1.7.1=py310hca03da5_1
  - python=3.10.19=hf701271_0
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-fastjsonschema=2.20.0=py310hca03da5_0
  - pyzmq=27.1.0=py310h5a8c52c_1
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=py310hca03da5_0
  - requests=2.32.5=py310hca03da5_1
  - rfc3339-validator=0.1.4=py310hca03da5_0
  - rfc3986-validator=0.1.1=py310hca03da5_0
  - rpds-py=0.28.0=py310h931abed_0
  - setuptools=80.9.0=py310hca03da5_0
  - six=1.17.0=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=py310hca03da5_0
  - terminado=0.18.1=py310hca03da5_0
  - tinycss2=1.4.0=py310hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - traitlets=5.14.3=py310hca03da5_0
  - typing-extensions=4.15.0=py310hca03da5_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - urllib3=2.5.0=py310hca03da5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.3.1
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - arrow==1.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - comm==0.2.3
      - debugpy==1.8.17
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fqdn==1.5.1
      - fsspec==2025.10.0
      - grpcio==1.76.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyterlab==4.4.10
      - jupyterlab-widgets==3.0.16
      - lark==1.3.1
      - markdown==3.10
      - markupsafe==3.0.3
      - mistune==3.1.4
      - mpmath==1.3.0
      - networkx==3.4.2
      - notebook==7.4.7
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - pillow==12.0.0
      - prometheus-client==0.23.1
      - protobuf==6.33.0
      - psutil==7.1.3
      - python-json-logger==4.0.0
      - pyyaml==6.0.3
      - rfc3987-syntax==1.1.0
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.8
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tomli==2.3.0
      - torch==2.9.0
      - torchvision==0.24.0
      - tornado==6.5.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.15
prefix: /opt/anaconda3/envs/jjxpytorchlearn
